######################################################################
# Automatically generated by qmake (3.0) ?r. gru 18 14:36:59 2013
######################################################################

TEMPLATE = lib
TARGET = v1.0
INCLUDEPATH += .

# Input
HEADERS += ElasticBodySimulator.h
SOURCES += ElasticBodySimulator.cpp
